export use bat-completions.nu *
export use cargo-completions.nu *
export use git-completions.nu *
export use less-completions.nu *
export use lstr-completions.nu *
export use make-completions.nu *
export use rg-completions.nu *
export use ssh-completions.nu *
export use tar-completions.nu *
export use vscode-completions.nu *
export use winget-completions.nu *
export use zoxide-completions.nu *
